### ISSUE TITLE
twilio upgrade giving an error

### ISSUE THREAD

**Issue by micuat** [hydra-synth/hydra#246]
due to dependabot dfdb4daf680484f70c8a5016d19d1571a862ca45

```
1|hydra    | /home/hydrogen/hydra/node_modules/twilio/lib/rest/Twilio.js:34
1|hydra    |         if (this.opts?.lazyLoading === false) {
1|hydra    |                       ^
1|hydra    | 
1|hydra    | SyntaxError: Unexpected token '.'
1|hydra    |     at wrapSafe (internal/modules/cjs/loader.js:1053:16)
1|hydra    |     at Module._compile (internal/modules/cjs/loader.js:1101:27)
1|hydra    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
1|hydra    |     at Module.load (internal/modules/cjs/loader.js:985:32)
1|hydra    |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
1|hydra    |     at Module.require (internal/modules/cjs/loader.js:1025:19)
1|hydra    |     at require (internal/modules/cjs/helpers.js:72:18)
1|hydra    |     at Object.<anonymous> (/home/hydrogen/hydra/node_modules/twilio/lib/index.js:28:34)
1|hydra    |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
1|hydra    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
1|hydra    | error Command failed with exit code 1.
```

I guess this notation is a newer JS standard - so maybe problem with the nodejs version?

**Comment by micuat** [comment]
requires node.js >=14.0.0

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
