### ISSUE TITLE
web-editor build fail due to hydra-synth

### ISSUE THREAD

**Issue by micuat** [hydra-synth/hydra#247]
```
hydrogen@blackmirror:~/hydra/frontend/web-editor$ /home/hydrogen/.nvm/versions/node/v12.18.3/bin/yarn build
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ browserify ./index.js --debug -o ./public/bundle.js && npm run uglify
Error: Parsing file /home/hydrogen/hydra/node_modules/hydra-synth/src/index.js: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Deps.parseDeps (/home/hydrogen/hydra/node_modules/module-deps/index.js:519:15)
    at getDeps (/home/hydrogen/hydra/node_modules/module-deps/index.js:447:44)
    at /home/hydrogen/hydra/node_modules/module-deps/index.js:430:38
    at ConcatStream.<anonymous> (/home/hydrogen/hydra/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:412:35)
    at finishMaybe (/home/hydrogen/hydra/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/hydrogen/hydra/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/hydrogen/hydra/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/home/hydrogen/hydra/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:519:28)
error Command failed with exit code 1.
```

**Comment by micuat** [comment]
I see people suggest using esmify but with `browserify ./index.js -p esmify` I see same errors :(
Is browserify anyways deprecated and we should use something else?

**Comment by micuat** [comment]
hydra-synth is supposed to be esmifying already, could it be that this part is not working??

**Comment by micuat** [comment]
I'm giving up investigating this issue because I can't really reproduce the error to determine which hydra-synth started to break this. After all, with any hydra-synth, browserify on web-editor fails on my environment :(

What I suggest is to switch the build environment to something modern like vite. Here is my test using choo and hydra
https://glitch.com/edit/#!/choo-hydra-vite

**Comment by micuat** [comment]
It seems like this line is causing an error (parent not defined) when I try to

1. build hydra-**synth** with vite+rollup
2. import umd build with script tag

https://github.com/hydra-synth/hydra-synth/blob/main/src/eval-sandbox.js#L18

if I comment it out, it works as normal (I don't know how it works in a live editor)

**Comment by ojack** [comment]
The error went away for me using esmify, I updated the main repo. 

hydra-synth is currently exporting to both commonJS and esm-style modules. The error was caused not by the module itself, but by directly importing the 'glsl-functions' file from `Mutator.js`. 

I still think we should continue to investigate this set of issues!

**Comment by ojack** [comment]
fixed for now by creating a separate glsl-functions file. 
I think we should still investigate all of this though!
